name: Github Actions 

on:
  pull_request:
    branches:
      - develop

jobs: 
  tests: 
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        node-version: [18.x, 20.x, 22.x]

    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 
      - name: Npm install 
        run: npm ci
      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          component: true 
